# Generated by Django 4.2.30 on 2026-07-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RsvpSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('response', models.CharField(choices=[('attending', 'Attending'), ('not_attending', 'Not attending')], max_length=20)),
                ('guest_count', models.PositiveSmallIntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
